### ISSUE TITLE
EndPoints

### ISSUE THREAD

**Issue by shaima96** [FACK1/wellSpent#24]
- [ ] ```GET /```
  -  Return Home page component which contains header section, search bar, and about us section)
- [ ] ```GET /search```
    - Get value from search input and send it to the backend
   - Get matched data from the database
   - Return response with matched data to frontEnd
   - Display result as a drop list  
- [ ] ```GET /brands```
   - Return all brands from database 
  -  Filter brands alphabetically 
  - Send a response to frontEnd 
  - We will get the response data by using axios and render it inside HTML.
- [ ] ```GET /brand/:id```
   -  Get the brand data from the database that includes:
   -  General data :labour score,environment score,animal right score,product type,cost ,explanation, 
        and the image 
       -  Get Feedback for each brand
  -   Send data to the client side by ```res.json()```
  -  In brand Component, we will get the brand data by use axios and render it inside HTML.
- [ ] ```POST /add_brand```
   - Get the suggested brand from frontEnd by creating a new brand form that includes brand details (name) and use onChange and onClick to submit the data.
  - Use axios to send the suggested brand from the client side.
  - Insert brand details into the database
  - Redirect to brands page
- [ ] ```POST /feedback```
  - Create a new feedback form that includes feedback details (name, comment) and use onChange and onClick to submit the data.
  - Use axios to send the feedback details from the client side.
  - Insert feedback details into the database
 - [ ] ```GET /about_us```
    - Get data from the database
    - send it to the fronEnd (about us component)
    - Display data in HomePage component

**Comment by m4v15** [comment]
Can I suggest: `GET /brand?name=nike`?

The chrome extension will scrape brand names from the website it is on (eg: https://www.asos.com/men/jackets-coats/cat/?cid=3606&ctaref=shop|jackets|mw_hp_categorytray) and then will only be able to query our server using brand names, so we need to allow this functionallity
